# Generated by Django 3.1.7 on 2021-04-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210402_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Determines whether the user is verified.', verbose_name='Is verified'),
        ),
    ]
