# Generated by Django 3.1.7 on 2021-04-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210402_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
