# Generated by Django 3.1.7 on 2021-04-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date_of_like',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of like'),
        ),
    ]
